"""
report_generator.py
Builds a downloadable PDF health report for a single prediction, using
ReportLab. Works for any disease defined in disease_config.py.
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from utils.disease_config import DISEASES, friendly_label


def generate_pdf_report(output_path, username, disease_key, input_data, result, probability, explanations):
    disease_label = DISEASES[disease_key]["label"]
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#1F3A5F"))
    section_style = ParagraphStyle("Section", parent=styles["Heading2"], textColor=colors.HexColor("#1F3A5F"))

    story = []
    story.append(Paragraph(f"AI-HealthGuard — {disease_label} Risk Report", title_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"Patient: {username}", styles["Normal"]))
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%d %b %Y, %I:%M %p')}", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Submitted Health Parameters", section_style))
    param_rows = [["Parameter", "Value"]] + [
        [friendly_label(disease_key, k), str(v)] for k, v in input_data.items()
    ]
    param_table = Table(param_rows, colWidths=[90 * mm, 60 * mm])
    param_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F3A5F")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
    ]))
    story.append(param_table)
    story.append(Spacer(1, 14))

    story.append(Paragraph("Prediction Result", section_style))
    result_color = colors.HexColor("#B00020") if result == "Positive" else colors.HexColor("#1B7A3D")
    result_style = ParagraphStyle("Result", parent=styles["Normal"], textColor=result_color, fontSize=13)
    story.append(Paragraph(f"{disease_label} Risk: <b>{result}</b> ({probability * 100:.1f}% probability)", result_style))
    story.append(Spacer(1, 14))

    story.append(Paragraph("Key Contributing Factors (Explainable AI)", section_style))
    exp_rows = [["Factor", "Value", "Effect"]] + [
        [e["feature"], str(e["value"]), e["impact"]] for e in explanations[:5]
    ]
    exp_table = Table(exp_rows, colWidths=[70 * mm, 30 * mm, 50 * mm])
    exp_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F3A5F")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
    ]))
    story.append(exp_table)
    story.append(Spacer(1, 16))

    disclaimer = ("Disclaimer: This report is generated by an AI model for educational/"
                  "screening purposes only and is not a medical diagnosis. Please consult "
                  "a qualified healthcare professional for clinical advice.")
    story.append(Paragraph(disclaimer, styles["Italic"]))

    doc.build(story)
    return output_path
